version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: tmi.js
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: phaser
    versions:
    - 3.52.0
    - 3.53.0
    - 3.53.1
  - dependency-name: pg-promise
    versions:
    - 10.9.2
    - 10.9.3
    - 10.9.4
  - dependency-name: socket.io
    versions:
    - 3.1.1
    - 3.1.2
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: discord.js
    versions:
    - 12.5.1
  - dependency-name: image-hash
    versions:
    - 4.0.1
  - dependency-name: moment
    versions:
    - 2.29.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: node-fetch
    versions:
    - 2.6.1
